{ config, pkgs, lib, ... }:

{

  # Containers
  virtualisation.oci-containers = {
    backend = "docker";
    containers = {

      karakeep-chrome = {
        image = "gcr.io/zenika-hub/alpine-chrome:123";
        cmd = [ 
        "--no-sandbox"
        "--disable-gpu"
        "--disable-dev-shm-usage"
        "--remote-debugging-address=0.0.0.0"
        "--remote-debugging-port=9222"
        "--hide-scrollbars"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=chrome"
          "--network=karakeep_default"
        ];
      };

      karakeep-meilisearch = {
        image = "getmeili/meilisearch:v1.13.3";
        environment = {
          "MEILI_NO_ANALYTICS" = "true";
        };
        environmentFiles = [ "${config.users.users.faust.home}/dotfiles/docker/karakeep/.env" ];
        volumes = [
          "${config.users.users.faust.home}/docker_volumes/karakeep/meilisearch:/meili_data:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=meilisearch"
          "--network=karakeep_default"
        ];
      };

      karakeep-web = {
        image = "ghcr.io/karakeep-app/karakeep:release";
        environment = {
          "BROWSER_WEB_URL" = "http://chrome:9222";
          "MEILI_ADDR" = "http://meilisearch:7700";
          "DATA_DIR" = "/data";
        };
        environmentFiles = [ "${config.users.users.faust.home}/dotfiles/docker/karakeep/.env" ];
        volumes = [
          "${config.users.users.faust.home}/docker_volumes/karakeep/data:/data:rw"
        ];
        ports = [
          "3001:3000/tcp"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=web"
          "--network=karakeep_default"
        ];
      };

    };
  };

  # Networks
  systemd.services."docker-network-karakeep_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f karakeep_default";
    };
    script = ''
      docker network inspect karakeep_default || docker network create karakeep_default
    '';
    partOf = [ "docker-compose-karakeep-root.target" ];
    wantedBy = [ "docker-compose-karakeep-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-karakeep-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
