services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: foundry_server
    container_name: foundry_main
    networks:
      - caddy
    volumes:
      - $HOME/docker_volumes/foundry_main_data:/data
    env_file:
      - $PWD/.env

networks:
  caddy:
    name: caddy
    external: true