{ config, pkgs, lib, ... }:

{

  # Agenix secrets
  age.secrets.your_spotify.file = ../../secrets/your_spotify.age;

  # Containers
  virtualisation.oci-containers = {
    backend = "docker";
    containers = {

      mongo = {
        image = "mongo:6";
        volumes = [
          "${config.users.users.faust.home}/docker_volumes/your_spotify_db:/data/db:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=mongo"
          "--network=your_spotify_default"
        ];
      };

      your_spotify-server = {
        image = "yooooomi/your_spotify_server";
        environmentFiles = [ config.age.secrets.your_spotify.path ];
        ports = [ "6000:8080/tcp" ];
        dependsOn = [
          "mongo"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=server"
          "--network=your_spotify_default"
        ];
      };

      your_spotify-web = {
        image = "yooooomi/your_spotify_client";
        environment = {
          "API_ENDPOINT" = "https://musicserver.hreddy.in";
        };
        ports = [ "6001:3000/tcp" ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=web"
          "--network=your_spotify_default"
        ];
      };

    };
  };

  # Systemd Services
  systemd.services = {

    docker-mongo = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-your_spotify_default.service"
      ];
      requires = [
        "docker-network-your_spotify_default.service"
      ];
      partOf = [
        "docker-compose-your_spotify-root.target"
      ];
      wantedBy = [
        "docker-compose-your_spotify-root.target"
      ];
    };

    docker-your_spotify-server = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-your_spotify_default.service"
      ];
      requires = [
        "docker-network-your_spotify_default.service"
      ];
      partOf = [
        "docker-compose-your_spotify-root.target"
      ];
      wantedBy = [
        "docker-compose-your_spotify-root.target"
      ];
    };

    docker-your_spotify-web = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-your_spotify_default.service"
      ];
      requires = [
        "docker-network-your_spotify_default.service"
      ];
        partOf = [
        "docker-compose-your_spotify-root.target"
      ];
      wantedBy = [
        "docker-compose-your_spotify-root.target"
      ];
    };

  };

  # Networks
  systemd.services."docker-network-your_spotify_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f your_spotify_default";
    };
    script = ''
      docker network inspect your_spotify_default || docker network create your_spotify_default
    '';
    partOf = [ "docker-compose-your_spotify-root.target" ];
    wantedBy = [ "docker-compose-your_spotify-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-your_spotify-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
