services:
  foundrytest:
    image: felddy/foundryvtt:release
    hostname: foundry_test
    container_name: foundry_test
    networks:
      - caddy
    volumes:
      - $HOME/docker_volumes/foundry_test_data:/data
    env_file:
      - $PWD/.env

networks:
  caddy:
    name: caddy
    external: true