# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{

  # Containers
  virtualisation.oci-containers = {
    backend = "docker";
    containers = {

      change_detection-browser-sockpuppet-chrome = {
        image = "dgtlmoon/sockpuppetbrowser:latest";
        environment = {
          "MAX_CONCURRENT_CHROME_PROCESSES" = "5";
          "SCREEN_DEPTH" = "16";
          "SCREEN_HEIGHT" = "1024";
          "SCREEN_WIDTH" = "1920";
        };
        log-driver = "journald";
        extraOptions = [
          "--cap-add=SYS_ADMIN"
          "--hostname=browser-sockpuppet-chrome"
          "--network-alias=browser-sockpuppet-chrome"
          "--network=change_detection_default"
        ];
      };

      changedetection = {
        image = "ghcr.io/dgtlmoon/changedetection.io";
        environment = {
          "DISABLE_VERSION_CHECK" = "true";
          "HIDE_REFERER" = "true";
          "MINIMUM_SECONDS_RECHECK_TIME" = "3";
          "PLAYWRIGHT_DRIVER_URL" = "ws://browser-sockpuppet-chrome:3000";
          "TZ" = "Asia/Calcutta";
        };
        volumes = [
          "/home/faust/docker_volumes/website_change_detection/:/datastore:rw"
          "/home/faust/dotfiles/docker/website_change_detection/proxies.json:/datastore/proxies.json:rw"
        ];
        ports = [ "5001:5000/tcp" ];
        log-driver = "journald";
        extraOptions = [
          "--hostname=changedetection"
          "--network-alias=changedetection"
          "--network=change_detection_default"
        ];
      };
    };
  };

  # Networks
  systemd.services."docker-network-change_detection_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f change_detection_default";
    };
    script = ''
      docker network inspect change_detection_default || docker network create change_detection_default
    '';
    partOf = [ "docker-compose-change_detection-root.target" ];
    wantedBy = [ "docker-compose-change_detection-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-change_detection-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
