services:
  mc-server:
    container_name: mc-server
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      MEMORY: 4G
      MOTD: Welcome to the server!
      SEED: 7599824378187852
      DIFFICULTY: NORMAL
      ENFORCE_WHITELIST: "TRUE"
      ONLINE_MODE: "TRUE"
      MAX_PLAYERS: 10
      WHITELIST_FILE: /extra/whitelist.json
      OPS_FILE: /extra/ops.json
      RCON_CMDS_STARTUP: |
        /gamerule keepInventory true
        /gamerule playersSleepingPercentage 0
        /gamerule disableElytraMovementCheck true
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
      MODRINTH_PROJECTS: |
        fabric-api
        carpet:f2mvlGrg
        lithium
        ferrite-core
        c2me-fabric
        modernfix
        appleskin
        clumps
        netherportalfix
        lmd
        always-a-wither-skull
        automatic-doors
        beautified-chat-server
        better-beacon-placement
        better-conduit-placement
        better-spawner-control
        compact-help-command
        dismount-entity
        easy-elytra-takeoff
        inventory-totem
        keep-my-soil-tilled
        no-animal-tempt-delay
        no-feather-trample
        quick-right-click
        replanting-crops
        scaffolding-drops-nearby
        softer-hay-bales
        sticky-enchanting-lapis
        thorny-bush-protection
        wool-tweaks
        zombie-proof-doors
    volumes:
      - $HOME/docker_volumes/minecraft/data:/data
      - $HOME/docker_volumes/minecraft/mods:/data/mods
      - $HOME/docker_volumes/minecraft/extra:/extra
