# Miscellaneous https://www.authelia.com/configuration/miscellaneous/introduction/
theme: auto

# First Factor https://www.authelia.com/configuration/first-factor/file/
authentication_backend:
  ldap:
    url: "ldap://lldap:3890"
    implementation: "custom"
    timeout: "5s"
    # start_tls: false
    base_dn: dc=example,dc=com
    username_attribute: uid
    additional_users_dn: "ou=people"
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    additional_groups_dn: "ou=groups"
    groups_filter: "(member={dn})"
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName

# Second Factor https://www.authelia.com/configuration/second-factor/introduction/
totp:
  issuer: authelia.com

# Security https://www.authelia.com/configuration/security/access-control/
access_control:
  default_policy: 'deny'
  rules:
  - domain: '*.hreddy.in'
    policy: 'one_factor'

# https://www.authelia.com/configuration/session/redis/
session:
  cookies:
  - domain: 'hreddy.in'
    authelia_url: 'https://auth.hreddy.in'
    name: 'authelia_session'
    expiration: '1 hour'
    inactivity: '5 minutes'

storage:
  # encryption_key: SECRETREPLACE3 #Generate long string numb/letters
  local:
    path: /home/faust/docker_volumes/authelia/db.sqlite3

# SMTP Notifier https://www.authelia.com/configuration/notifications/smtp/
# Set also AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
notifier:
  smtp:
    username: 'himavanth.reddy19@gmail.com'
    sender: 'authelia@hreddy.in'
    address: 'submission://smtp.gmail.com:587'
