{ pkgs, lib, ... }:

{
  # Containers
  virtualisation.oci-containers = {
    backend = "docker";
    containers = {
      authelia = {
        image = "authelia/authelia:latest";
        ports = [ "9091:9091" ];
        environment = {
          "AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE" = "/config/secrets/JWT_SECRET";
          "AUTHELIA_SESSION_REDIS_PASSWORD_FILE" = "/config/secrets/REDIS_PASSWORD";
          "AUTHELIA_SESSION_SECRET_FILE" = "/config/secrets/SESSION_SECRET";
          "AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE" = "/config/secrets/STORAGE_ENCRYPTION_KEY";
        };
        volumes = [
          "/home/faust/docker_volumes/authelia/config:/config:rw"
        ];
        dependsOn = [
          "redis_authelia"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=authelia"
          "--network=authelia_authelia"
        ];
      };

      redis_authelia = {
        image = "redis:7-alpine";
        volumes = [
          "/home/faust/docker_volumes/authelia/redis:/data:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=redis"
          "--network=authelia_authelia"
        ];
      };
    };
  };

  # Networks
  systemd.services."docker-network-authelia_authelia" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f authelia_authelia";
    };
    script = ''
      docker network inspect authelia_authelia || docker network create authelia_authelia --driver=bridge
    '';
    partOf = [ "docker-compose-authelia-root.target" ];
    wantedBy = [ "docker-compose-authelia-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-authelia-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
