{ config, pkgs, lib, ... }:

{
  # Containers
  virtualisation.oci-containers = {
    backend = "docker";
    containers = {
      authelia = {
        image = "authelia/authelia:latest";
        ports = [ "9091:9091" ];
        environmentFiles = [ "/home/faust/dotfiles/docker/authelia/.env" ];
        volumes = [
          "${config.users.users.faust.home}/dotfiles/docker/authelia/configuration.yml:/config/configuration.yml:rw"
          "${config.users.users.faust.home}/dotfiles/docker/authelia/users_database.yml:/config/users_database.yml:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=authelia"
          "--network=authelia_authelia"
        ];
      };

    };
  };

  # Networks
  systemd.services."docker-network-authelia_authelia" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f authelia_authelia";
    };
    script = ''
      docker network inspect authelia_authelia || docker network create authelia_authelia --driver=bridge
    '';
    partOf = [ "docker-compose-authelia-root.target" ];
    wantedBy = [ "docker-compose-authelia-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-authelia-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
