{ config, pkgs, lib, ... }:

{

  # Containers
  virtualisation.oci-containers = {
    backend = "docker";
    containers = {

      immich_machine_learning = {
        image = "ghcr.io/immich-app/immich-machine-learning:release";
        environmentFiles = [ "${config.users.users.faust.home}/dotfiles/docker/immich/.env" ];
        volumes = [
          "${config.users.users.faust.home}/docker_volumes/immich/model-cache:/cache:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=immich-machine-learning"
          "--network=immich_default"
        ];
      };

      immich_postgres = {
        image = "ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0";
        environmentFiles = [ "${config.users.users.faust.home}/dotfiles/docker/immich/.env" ];
        volumes = [
          "${config.users.users.faust.home}/docker_volumes/immich/postgres:/var/lib/postgresql/data:rw"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=database"
          "--network=immich_default"
        ];
      };

      immich_redis = {
        image = "docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177";
        log-driver = "journald";
        extraOptions = [
          "--health-cmd=redis-cli ping || exit 1"
          "--network-alias=redis"
          "--network=immich_default"
        ];
      };

      immich_server = {
        image = "ghcr.io/immich-app/immich-server:release";
        environmentFiles = [ "${config.users.users.faust.home}/dotfiles/docker/immich/.env" ];
        volumes = [
          "/etc/localtime:/etc/localtime:ro"
          "/home/faust/docker_volumes/immich/photos:/usr/src/app/upload:rw"
          "/home/faust/photos:/usr/src/app/external/photos:rw"
        ];
        ports = [ "2283:2283/tcp" ];
        dependsOn = [
          "immich_postgres"
          "immich_redis"
        ];
        log-driver = "journald";
        extraOptions = [
          "--network-alias=immich-server"
          "--network=immich_default"
        ];
      };
    };
  };

  # Networks
  systemd.services."docker-network-immich_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f immich_default";
    };
    script = ''
      docker network inspect immich_default || docker network create immich_default
    '';
    partOf = [ "docker-compose-immich-root.target" ];
    wantedBy = [ "docker-compose-immich-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-immich-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
